version: '2'
services:
  server:
    container_name: ttt-server         # Set name of the container
    environment:                       # Set exported env. variables
      - 'PORT=80'                      # Listening port for the http server
      - 'NODE_ENV=production'          # Runtime mode of the server
      - 'PGUSER=postgres'              # Productin DB user/pass/host info
      - 'PGPASSWORD=CVakcK22D4pntv7Y'
      - 'PGUSER=pg-prod'
    image: 'sveinn/tictactoe'          # Define which image to use
    build:                             # Build info if needed
      context: '.'
      dockerfile: 'Dockerfile'
    ports:
      - '80:80'                        # Which port to expose (and map)
    links:
      - 'pg-prod'                      # Build network link to pg-prod container
    depends_on:
      - "pg-prod"                      # Make container dependent on database (db starts first)
  pg-prod:
    container_name: ttt-database
    environment:
      - 'POSTGRES_PASSWORD=CVakcK22D4pntv7Y'   # Set the postgres password
    image: postgres
