version: '2'
services:
  server:
    container_name: ttt-server
    environment:
      - 'NODE_ENV=production'
      - 'DATABASE_PROD_USER=postgres'
      - 'DATABASE_PROD_PASS=CVakcK22D4pntv7Y'
      - 'DATABASE_PROD_HOST=pg-prod'
    image: 'sveinn/tictactoe'
    build:
      context: '.'
      dockerfile: 'Dockerfile'
    ports:
      - '8080:8080'
    links:
      - 'pg-prod'
    depends_on:
      - "pg-prod"
  pg-prod:
    container_name: ttt-database
    environment:
      - 'POSTGRES_PASSWORD=CVakcK22D4pntv7Y'
    image: postgres
